<?php
/******************************************
FR French
Admin Category Language
******************************************/

$lang['categories']					= 'Catégories';
$lang['error_must_select']			= 'Vous devez sélectionner une catégorie pour pouvoir les re-organiser';
$lang['error_not_found']			= 'La catégorie demandée n\'a pas pu être trouvé.';
$lang['organize_category']			= 'Organiser "%s" catégorie';
$lang['organize']					= 'Organiser';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Formulaire pour créer une nouvelle catégorie';
$lang['name']						= 'Nom';
$lang['slug']						= 'Slug';
$lang['description']				= 'Description';
$lang['excerpt']					= 'Extrait';
$lang['sequence']					= 'Séquence';
$lang['image']						= 'Image';
$lang['seo_title']					= 'SEO Titre';
$lang['meta']						= 'Métadonnées';
$lang['message_category_saved']		= 'La catégorie a été sauvé!';
$lang['error_file_upload']			= '<p>Vous n\'avez pas sélectionné de fichier à télécharger.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'La catégorie a été supprimée.';
$lang['current_file']				= 'Fichier en cours';
$lang['confirm_delete_category']	= 'Etes-vous sûr de vouloir supprimer cette catégorie?';
$lang['add_new_category']			= 'Ajouter une nouvelle catégorie';
$lang['no_categories']				= 'Il n\'y a pas de catégories actuellement';
$lang['attributes']					= 'Attributs';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="Nous vendons des produits d\'enfants" /&gt;';
$lang['drag_and_drop']				= 'Glissez et déposez les produits dans l\'ordre que vous souhaitez qu\'ils apparaissent.';
$lang['sku']						= 'SKU';
$lang['price']						= 'Prix';
$lang['original']					= 'Prix d\origine';
$lang['sale']						= 'Prix réduit';
$lang['solde']						= 'Prix solde';
$lang['max_file_size']				= 'Taille de fichier max';